Name:           ros-indigo-gazebo-state-plugins
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS gazebo_state_plugins package

Group:          Development/Libraries
License:        GPLv3
Source0:        %{name}-%{version}.tar.gz

Requires:       gazebo-devel
Requires:       ros-indigo-eigen-conversions
Requires:       ros-indigo-gazebo-ros
Requires:       ros-indigo-gazebo-world-plugin-loader
Requires:       ros-indigo-geometry-msgs
Requires:       ros-indigo-nav-msgs
Requires:       ros-indigo-object-msgs
Requires:       ros-indigo-object-msgs-tools
Requires:       ros-indigo-roscpp
Requires:       ros-indigo-shape-msgs
Requires:       ros-indigo-std-msgs
BuildRequires:  gazebo-devel
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-eigen-conversions
BuildRequires:  ros-indigo-gazebo-ros
BuildRequires:  ros-indigo-gazebo-world-plugin-loader
BuildRequires:  ros-indigo-geometry-msgs
BuildRequires:  ros-indigo-nav-msgs
BuildRequires:  ros-indigo-object-msgs
BuildRequires:  ros-indigo-object-msgs-tools
BuildRequires:  ros-indigo-roscpp
BuildRequires:  ros-indigo-shape-msgs
BuildRequires:  ros-indigo-std-msgs

%description
Offers topics and services related to the state of the world in Gazebo.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Sat Jan 06 2018 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.2-0
- Autogenerated by Bloom

* Wed Jun 08 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.1-0
- Autogenerated by Bloom

* Tue Jun 07 2016 Jennifer Buehler <jennifer.e.buehler@gmail.com> - 1.0.0-0
- Autogenerated by Bloom

